source 'https://rubygems.org'

gem 'bootstrap-sass'
gem 'coffee-rails', '~> 4.2'
gem 'haml-rails'
gem 'jbuilder', '~> 2.5'
gem 'jquery-rails'
gem 'mysql2'
gem 'nokogiri'
gem 'pry'
gem 'puma', '~> 3.0'
gem 'rails', '~> 5.0.0'
gem 'sass-rails', '~> 5.0'
gem 'spring'
gem 'spring-watcher-listen', '~> 2.0.0'
gem 'turbolinks', '~> 5'
gem 'uglifier', '>= 1.3.0'
