# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ef47b046058324eb7a2f29031dd732ede564e2c9fd3db1d2e0a47712161d8ff7f6d8e9c500688b6aec09d081d8c00aaab4770f6ca53ceaef0cae2f481886b79d

test:
  secret_key_base: 2c8057d0c79145e3bc20511fb5515cbaa064eb5707a824f85bb18ae9967b0604b17b52ceac6922579004270b6f616f6f796e48ff56c5aea8bdf8e0752a31e223

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
